# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-21 13:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apptests', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answerbody',
            name='answer_to_type',
        ),
        migrations.RemoveField(
            model_name='questionbody',
            name='question_answer_count',
        ),
        migrations.RemoveField(
            model_name='questionbody',
            name='question_right_answer_count',
        ),
        migrations.RemoveField(
            model_name='questionbody',
            name='question_to_answer',
        ),
        migrations.RemoveField(
            model_name='simplechoice',
            name='choice_to_answer',
        ),
        migrations.RemoveField(
            model_name='tabletask',
            name='task_to_answer',
        ),
        migrations.AddField(
            model_name='questionbody',
            name='question_annotation',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='simplechoice',
            name='choice_to_question',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='apptests.QuestionBody'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tabletask',
            name='task_to_question',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='apptests.QuestionBody'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='AnswerBody',
        ),
        migrations.DeleteModel(
            name='AnswerType',
        ),
    ]
