# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-26 15:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('payment_for_type', models.CharField(default='Creative tasks', max_length=100)),
                ('transaction_amount', models.FloatField()),
                ('transaction_date', models.DateTimeField()),
                ('transaction_status', models.CharField(default='Not paid', max_length=30)),
            ],
        ),
    ]
