# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-26 15:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreativeTaskAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('task_id', models.IntegerField()),
                ('status', models.CharField(default='processing', max_length=20)),
                ('rate', models.IntegerField()),
                ('remark', models.CharField(max_length=1500)),
            ],
        ),
        migrations.CreateModel(
            name='TestAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_id', models.IntegerField()),
                ('question_id', models.IntegerField()),
                ('choice_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('is_true', models.BooleanField()),
            ],
        ),
    ]
