# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-28 20:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creativetaskanswer',
            name='rate',
            field=models.IntegerField(default=0),
        ),
    ]
