# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-12 09:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statsapp', '0003_requestrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.CharField(max_length=32)),
                ('method', models.CharField(max_length=10)),
                ('uri', models.CharField(max_length=256)),
                ('params', models.CharField(max_length=2500)),
                ('timestamp', models.DateTimeField(default=datetime.datetime.utcnow)),
                ('status', models.IntegerField(default=200)),
                ('errors', models.CharField(default='{}', max_length=2500)),
            ],
        ),
        migrations.DeleteModel(
            name='RequestRecord',
        ),
    ]
